// Example sketch showing how on ESP32, ESP32-S2 and ESP32-S3:
//
// 1. Set up memory write protection (a variable in this example) (see esp_cpu_set_watchpoint())
// 2. Skip an instruction (debug_exception_handler)
// 3. Handle a high-priority interrupt (di.S)
//
// A breakpoint can be set and intercepted in a similar way (see esp_cpu_set_breakpoint()).
// DBREAK and IBREAK can be combined for controlled single-step execution.

#include <Arduino.h>

// Exception Frame.
//
struct exc_frame {
  uint32_t ps;
  uint32_t pc;            // pointer to the instruction that triggered the interrupt
  uint32_t registers[20];
};


extern "C" void debug_exception_handler(struct exc_frame *frame);

// Interrupt trigger counter
static int triggered = 0;

// Address of the instruction that triggered the interrupt
static uintptr_t address = 0;

// DebugInterrupt handler. (Generated by the CPU when protected memory is accessed)
// Data watchpoints and code breakpoints arrive here, but in this example
// we only handle data watchpoints.
// Skips the instruction that triggered the interrupt and increments
// the event counter.
// Called from di.S, parameters are passed via stack.
//
void IRAM_ATTR debug_exception_handler(struct exc_frame *f) {

  // Instruction length lookup table.
  // Instruction length determined by its first byte.
  // Length may vary from 2 to 4 bytes, including 3-byte instructions.
  //
  static const uint8_t xt_insn_len[] = { XCHAL_BYTE0_FORMAT_LENGTHS };

  // PC register = address of the instruction that triggered the interrupt.
  // Read the first instruction byte through IBUS. Harvard architecture after all.
  //
  // 1. IBUS requires aligned 32-bit access.
  // 2. Xtensa instructions can be 2, 3, or 4 bytes long.
  //
  // Therefore we read an aligned word and then shift it.
  // No other option — otherwise the CPU will hang.
  //
  // The first instruction byte (`opcode`) determines the instruction length.
  //
  uintptr_t pc = (uintptr_t)f->pc;

  // Save the address of the instruction that triggered the interrupt
  address = pc;

  uint32_t aligned = pc & ~3;
  uint32_t word = *(volatile uint32_t *)aligned;
  uint32_t shift = (pc & 3) * 8;
  uint8_t opcode = (word >> shift) & 255;

  // Skip the instruction
  f->pc = f->pc + xt_insn_len[opcode];

  // Or this way, if we do not want to skip it:
  // esp_cpu_clear_watchpoint(0);
  //

  // Increment the counter
  triggered++;
}


// Test variable. This one will be protected.
// volatile so the compiler doesn't optimize it away
static volatile int test = 666;


void setup() {

  Serial.begin(115200);

  // Enable protection using ESP-IDF:
  // Watchpoint#0, variable test, length = 4 bytes
  //
  // Length may be from 1 to 64 bytes, but the address must be aligned
  // to the protection size. For example, a 16-byte array must be aligned
  // on a 16-byte boundary. __attribute__((aligned)) to the rescue.
  //
  // Watchpoint#1 is already occupied by FreeRTOS and there are no others.
  // There are only two hardware watchpoints available.
  //
  esp_cpu_set_watchpoint(0, (const void *)&test, 4 , ESP_CPU_WATCHPOINT_STORE);
}


void loop() {

  // Write into protected memory:
  // this should trigger an interrupt and invoke debug_exception_handler().
  //
  // The variable value will NOT change because our handler simply skips
  // the instruction.
  //
  // The handler may re-execute the instruction — in that case there is no
  // need to modify PC, but esp_cpu_clear_watchpoint(0) should be called.
  //
  // Otherwise, after re-executing the instruction, another interrupt will
  // immediately be generated and so on forever.
  //
  test = triggered;

  // A sketch without delay is not a sketch.
  delay(1000);

  // Expected output (an example): "Triggered=321, test=666, address=4200xxxx"
  Serial.printf("Triggered=%d, test=%d, address=%x\r\n", triggered, test, address);

}
